### PR TITLE
adds handling of stories wrapped with info addon

### LINKED ISSUE #11: SmartKnobs does not work with Info
Info and SmartKnobs doesn't seem to work together. When I replace `addWithInfo` with `add`, the SmartKnobs appear in the Knobs panel. It doesn't otherwise.

```
import React from 'react';
import { storiesOf } from '@storybook/react';
const ProgressBar = require('shared/components/ProgressBar');

import { withSmartKnobs } from 'storybook-addon-smart-knobs';
import { withKnobs } from '@storybook/addon-knobs';

storiesOf('ProgressBar', module)
  .addDecorator(withSmartKnobs)
  .addDecorator(withKnobs)
  .addWithInfo('default style', () => (
    <ProgressBar />
  ));

```

### PR DESCRIPTION
**Pull request by flipace**
This PR adds a hacky but working solution to handle the combination of smart knobs and info addon.

I'm checking whether specific props which are added by the info addon are available on the component and if yes, the addon will check the props of the child component instead and then clone both - the root and child component - in order to replace the props on the correct component.

(the problem was that the info addon wraps the stories with another component which in turn leads to smart knobs not recognizing the props of the child component)

This fixes #11 

Let me know whether I should add/change something! Cheers 👍

### CODE REVIEW

**Comment by husayt** [comment]
let's get it merged please. thanks @flipace

**Review by danielduan — APPROVED** [review]

**Comment by danielduan** [comment]
This looks about right to be, would like a second pair of eyes on these before merging though.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
screen shot 2017-09-26 at 07 51 20

**Comment by ndelangen** [comment]
published as:
`storybook-addon-smart-knobs@3.2.10`

**Comment by ndelangen** [comment]
Thank you @flipace !!

**Comment by flipace** [comment]
This is pretty awesome. I've been working on a small babel plugin which auto-generates stories for us - and the more things we can automatically display without adding any additional code, the better 👍  Love what you guys did with storybook, it got really powerful in the last year! https://github.com/flipace/babel-plugin-generate-stories

**Pull request merged**
