### PR TITLE
v4.0.0

### PR DESCRIPTION
**Pull request by cdierkens**
Update to the latest storybook and resolve peer dependencies.

### CODE REVIEW

**Comment by rpellerin** [comment]
Can this please get merged?

**Comment by rpellerin** [comment]
@ndelangen ?

**Comment by ndelangen** [comment]
O damn, wish I had seen this earlier, my notifications have been so trashed lately I missed this.

I just published 4.0.0 with pretty much these changes in it.

@cdierkens & @rpellerin if you want to check if it works for you, maybe I missed something?

**Comment by rpellerin** [comment]
No problem :)
Works for me, thank you so much @ndelangen! I don't see `@babel/preset-env` in the dev dependencies though, is this intentional?

**Comment by ndelangen** [comment]
Uhm, if it's missing, that's a bug. care to fix it in a PR?

**Comment by rpellerin** [comment]
There you go: https://github.com/storybooks/addon-smart-knobs/pull/38

**Pull request closed without merging**
