### PR TITLE
Groups of knobs to organize multiple components on the same page

### PR DESCRIPTION
**Pull request by bastienrobert**
If the same component is several times in the same story, groups are automatically generated based on the children's index in order to put them in tabs and prevent conflicts between props.

Also, it fix the documentation page issue in storybook/addon-knobs.

Maybe it would be possible to customize these names to make groups more verbose.

Fix. https://github.com/storybookjs/addon-smart-knobs/issues/71

### CODE REVIEW

**Comment by bastienrobert** [comment]
About this:
> Maybe it would be possible to customize these names to make groups more verbose.

Maybe we could read a props on children components (like `__groupId`) in the stories to get more verbose names?

**Comment by bastienrobert** [comment]
Seems like I'm having another issue when using addon-docs. If component is not wrapped, it doesn't receive props properly in the doc page. 
I have to do something like:
```js
const Wrapper = (props) => <MyComponent {...props} />

export const Story = () => <Wrapper foo="bar" />
```

I just don't understand why it does have this behavior.

**Comment by ndelangen** [comment]
Could you merge in the base branch please?

**Comment by bastienrobert** [comment]
I just did it @ndelangen but maybe it'll be necessary to check this : https://github.com/storybookjs/addon-smart-knobs/pull/75#issuecomment-602032718 and to fix this : https://github.com/storybookjs/addon-smart-knobs/pull/75#issuecomment-602291443 ?

**Comment by ndelangen** [comment]
That's strange, that behavior should just work, I think you're using CSF there?

**Comment by bastienrobert** [comment]
Yes I am. I just wanted to start with a basic setup before looking to make it works with MDX Syntax (because I'm using Typescript).

Maybe another PR to add more documentation on how to setup Storybook docs with Typescript and MDX here [storybook docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#typescript-configuration ) could be cool ?

**Comment by ndelangen** [comment]
@shilman is working on a replacement for knobs that has this auto-feature built-in btw.

Any PR improving the docs would be welcome!

**Comment by bastienrobert** [comment]
Ok, that's cool! Maybe you have a date for a release? 🙃

**Comment by ndelangen** [comment]
6.0.0 is scheduled for release next month or so. It depends on how many bugs we find during prereleases.

**Comment by nikshevchenko** [comment]
Hi, folks! Can you talk about the status of this PR? I using 6.0.2 but I have the same problems with my multiple components.

**Comment by chriszarate** [comment]
Just a note that Storybook v6 and `@storybook/addon-essentials` have been released, including the ["Controls"](https://storybook.js.org/docs/react/essentials/controls) addon. You can think of Controls as smart knobs, with the added benefit that they can be embedded on Docs pages using `ArgsTable`.

I am not a maintainer, but I'd consider this addon effectively dead since Controls have resolved all open issues I had with Smart Knobs (including this one) and leapfrogged it in terms of functionality.

**Comment by bastienrobert** [comment]
I agree with @chriszarate, this PR is clearly useless for v6 because this addon is useless for v6.

@nikshevchenko I don't think having multiple components in the same story is a good practice. Is your code opensource or could you setup a bug repro? Can't help without more informations.

@ndelangen is this repo going to be archived or do you want to keep it active? Maybe this question should be in another issue?

**Review by jimmyandrade — APPROVED** [review]

**Comment by ndelangen** [comment]
@bastienrobert I think it's best archived, I'll ask @shilman

**Pull request closed without merging**
