### PR TITLE
feat: support for react-docgen-typescript-loader

### LINKED ISSUE #25: TypeScript support?
Do you have a plan to support to TypeScript?

### PR DESCRIPTION
**Pull request by nekitk**
Fixes https://github.com/storybookjs/addon-smart-knobs/issues/25

* create knobs from docgen info generated by react-docgen-typescript-loader
* use defaultValue from docgen to set starting value in knob
* moves table with prop types to separate component for reuse

### CODE REVIEW

**Comment by nekitk** [comment]
@ndelangen hi! could you please take a look at these PRs? (https://github.com/storybookjs/addon-smart-knobs/pull/61 & https://github.com/storybookjs/addon-smart-knobs/pull/60)
We are currently forced to use our own fork with these PRs merged.

**Comment by ndelangen** [comment]
@nekitk This package has gone a bit neglected, I'm sorry. Would you be interested in helping maintain this?

I've invited you to the github org, this should give you the ability to merge these.

**Comment by nekitk** [comment]
@ndelangen sure, thanks!

**Comment by nekitk** [comment]
@ndelangen Hi! I've merged some of the opened pull requests. Could you please publish a new version? Note that there were a breaking change in https://github.com/storybookjs/addon-smart-knobs/pull/65 — decorator usage changed from `withSmartKnobs` to `withSmartKnobs(options)`.

**Comment by ndelangen** [comment]
@nekitk what's you npm account url?

**Comment by ndelangen** [comment]
So release a new major version?

**Comment by nekitk** [comment]
@ndelangen 

> @nekitk what's you npm account url?

https://www.npmjs.com/~nekitk

> So release a new major version?

yes, as it has broken backward compatibility

**Comment by ndelangen** [comment]
@nekitk enable 2FA for your npm account and you should be able to publish to https://www.npmjs.com/package/storybook-addon-smart-knobs 👍

**Comment by nekitk** [comment]
@ndelangen released a new version 6.0.0, thanks!

**Comment by stephenkoo** [comment]
Hi @nekitk, for clarification if I've `react-docgen-typescript-loader` in `.storybook/main.js` like instructed in the [docs](https://storybook.js.org/docs/configurations/typescript-config/), do I still need to do the configuration steps for `babel-plugin-react-docgen` in the [smart knob README](https://github.com/storybookjs/addon-smart-knobs/#configuration)?

My main.js:
```js
module.exports = {
  stories: ["../src/**/*.stories.(tsx|mdx)"],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve("babel-loader"),
          options: {
            presets: [["react-app", { flow: false, typescript: true }]],
          },
        },
        {
          loader: require.resolve("react-docgen-typescript-loader"),
          options: {
            tsconfigPath: path.resolve(__dirname, "../tsconfig.json"),
          },
        },
      ],
    });
    config.resolve.extensions.push(".ts", ".tsx");
    return config;
  },
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-essentials",
    "@storybook/addon-actions",
    "@storybook/addon-knobs",
    "@storybook/addon-docs",
    "@storybook/addon-links",
  ],
};
```


And would preloading globally in `preview.js` work like so:
```js
import { addDecorator } from '@storybook/react';
import { withKnobs } from "@storybook/addon-knobs";
import { withSmartKnobs } from 'storybook-addon-smart-knobs'

/**
 * May need additional config
 * https://github.com/storybookjs/addon-smart-knobs#configuration
 */
addDecorator(withSmartKnobs())
addDecorator(withKnobs);
```

**Comment by nekitk** [comment]
> Hi @nekitk, for clarification if I've `react-docgen-typescript-loader` in `.storybook/main.js` like instructured in the [docs](https://storybook.js.org/docs/configurations/typescript-config/), do I still need to do the configuration steps for `babel-plugin-react-docgen` in the [smart knob README](https://github.com/storybookjs/addon-smart-knobs/#configuration)?

Hi! No, you don't need to configure `babel-plugin-react-docgen` with typescript. You should add `shouldExtractLiteralValuesFromEnum: true` to the options of `react-docgen-typescript-loader` for richer enum support.

Preloading globally should work.

**Comment by stephenkoo** [comment]
Thank you! I appreciate your work on this.

**Pull request merged**
